//! Contract bytecode generation and dependency orchestration.

use crate::{
    Backend, EvmCodegen,
    backend::evm::{EIP170_RUNTIME_CODE_SIZE_LIMIT, ir},
    lower,
    mir::Module,
    pass::run_pipeline,
};
use alloy_primitives::Bytes;
use either::Either;
use solar_ast::TypeSize;
use solar_config::{EvmVersion, OptimizationMode};
use solar_data_structures::{
    bit_set::{DenseBitSet, GrowableBitSet},
    index::IndexVec,
    map::FxHashMap,
    sync::{self, Scope},
};
use solar_interface::Result;
use solar_sema::{
    Gcx,
    hir::{ContractId, VariableId},
};
use std::sync::{
    OnceLock,
    atomic::{AtomicUsize, Ordering},
};

/// Generated bytecode and optional intermediate representations for one contract.
#[derive(Clone, Debug, Default)]
pub struct ContractArtifact {
    /// Deployment bytecode.
    pub deployment: Bytes,
    /// Runtime bytecode.
    pub runtime: Bytes,
    /// Immutable placeholders in the runtime bytecode.
    pub immutable_references: Vec<ImmutableReference>,
    /// Captured MIR, built under `-O none` when no explicit pipeline is configured and
    /// post-pipeline otherwise.
    pub mir: Option<Module>,
    /// Final deployment-prefix EVM IR immediately before byte emission.
    pub deployment_evm_ir: Option<ir::Module>,
    /// Final runtime EVM IR immediately before byte emission.
    pub runtime_evm_ir: Option<ir::Module>,
}

/// An immutable placeholder in runtime bytecode.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ImmutableReference {
    /// Source variable containing the immutable declaration.
    pub variable_id: VariableId,
    /// Byte offset where the placeholder data begins.
    pub start: usize,
    /// Type width encoded by the placeholder.
    pub type_size: TypeSize,
}

/// A contract selection.
#[derive(Clone, Debug)]
pub enum ContractSelection {
    /// Generate only the listed contracts and their dependencies.
    Specific(DenseBitSet<ContractId>),
    /// Generate every deployable contract.
    All,
}

impl ContractSelection {
    /// Creates an empty contract selection.
    pub fn empty(gcx: Gcx<'_>) -> Self {
        Self::Specific(DenseBitSet::new_empty(gcx.hir.contract_ids().len()))
    }

    /// Returns the specific contracts or every deployable contract.
    pub fn into_iter<'a, 'gcx>(
        &'a self,
        gcx: Gcx<'gcx>,
    ) -> impl Iterator<Item = ContractId> + use<'a, 'gcx> {
        match self {
            Self::Specific(contracts) => Either::Left(contracts.iter()),
            Self::All => Either::Right(gcx.hir.contract_ids().filter(move |&contract_id| {
                let contract = gcx.hir.contract(contract_id);
                !contract.kind.is_interface() && !contract.kind.is_abstract_contract()
            })),
        }
    }

    /// Adds another selection to this one.
    pub fn union_with(&mut self, other: &Self) {
        match other {
            Self::Specific(other) => {
                if let Self::Specific(contracts) = self {
                    contracts.union(other);
                }
            }
            Self::All => *self = Self::All,
        }
    }

    /// Selects `contract_id`.
    pub fn insert(&mut self, contract_id: ContractId) {
        if let Self::Specific(contracts) = self {
            contracts.insert(contract_id);
        }
    }

    /// Returns whether no contracts are selected.
    pub fn is_empty(&self) -> bool {
        matches!(self, Self::Specific(contracts) if contracts.is_empty())
    }

    /// Returns whether `contract_id` is selected.
    fn contains(&self, contract_id: ContractId) -> bool {
        match self {
            Self::Specific(contracts) => contracts.contains(contract_id),
            Self::All => true,
        }
    }
}

/// Generates requested contract artifacts and their creation-bytecode dependencies.
///
/// Contracts in `contracts` retain bytecode in the returned artifact.
/// Contracts in `capture_mir` retain built MIR under `-O none` when no explicit pipeline is
/// configured and final MIR otherwise.
/// Contracts in `capture_evm_ir` retain their final EVM IR in the returned artifact.
pub fn generate_contract_bytecodes(
    gcx: Gcx<'_>,
    contracts: &ContractSelection,
    capture_mir: &ContractSelection,
    capture_evm_ir: &ContractSelection,
) -> Result<FxHashMap<ContractId, ContractArtifact>> {
    let captures =
        ContractCaptures { bytecode: contracts, mir: capture_mir, evm_ir: capture_evm_ir };
    let mut requested = contracts.clone();
    requested.union_with(capture_mir);
    requested.union_with(capture_evm_ir);
    let graph = ContractGraph::discover(gcx, &requested)?;
    let contract_count = gcx.hir.contract_ids().len();
    let artifacts =
        IndexVec::<ContractId, _>::from_vec((0..contract_count).map(|_| OnceLock::new()).collect());
    let remaining_dependencies = IndexVec::<ContractId, _>::from_vec(
        graph
            .dependencies
            .iter()
            .map(|dependencies| AtomicUsize::new(dependencies.len()))
            .collect(),
    );

    let mut ready = DenseBitSet::new_empty(contract_count);
    for contract_id in graph.reachable.iter() {
        if graph.dependencies[contract_id].is_empty() {
            ready.insert(contract_id);
        }
    }

    // Pass debugging writes directly to stdout and stderr, so keep its output ordered.
    let parallel = gcx.sess.is_parallel()
        && !gcx.sess.opts.unstable.print_after_each
        && !gcx.sess.opts.unstable.pass_diff
        && !gcx.sess.opts.unstable.time_passes;
    sync::scope(parallel, |scope| {
        for contract_id in ready.iter() {
            spawn_contract_codegen(
                &scope,
                gcx,
                captures,
                &graph,
                &artifacts,
                &remaining_dependencies,
                contract_id,
            );
        }
    });
    gcx.dcx().has_errors()?;

    let mut generated = FxHashMap::default();
    for (contract_id, artifact) in artifacts.into_iter_enumerated() {
        if graph.reachable.contains(contract_id) {
            generated.insert(
                contract_id,
                artifact.into_inner().expect("contract artifact should have been generated"),
            );
        }
    }
    Ok(generated)
}

#[derive(Clone, Copy)]
struct ContractCaptures<'a> {
    bytecode: &'a ContractSelection,
    mir: &'a ContractSelection,
    evm_ir: &'a ContractSelection,
}

struct ContractGraph {
    dependencies: IndexVec<ContractId, GrowableBitSet<ContractId>>,
    dependents: IndexVec<ContractId, Vec<ContractId>>,
    reachable: DenseBitSet<ContractId>,
}

impl ContractGraph {
    fn discover(gcx: Gcx<'_>, contracts: &ContractSelection) -> Result<Self> {
        let contract_count = gcx.hir.contract_ids().len();
        let mut graph = Self {
            dependencies: IndexVec::from_vec(
                (0..contract_count).map(|_| GrowableBitSet::new_empty()).collect(),
            ),
            dependents: IndexVec::from_vec((0..contract_count).map(|_| Vec::new()).collect()),
            reachable: DenseBitSet::new_empty(contract_count),
        };
        let mut visiting = DenseBitSet::new_empty(contract_count);
        for contract_id in contracts.into_iter(gcx) {
            graph.discover_contract(gcx, contract_id, &mut visiting)?;
        }
        Ok(graph)
    }

    fn discover_contract(
        &mut self,
        gcx: Gcx<'_>,
        contract_id: ContractId,
        visiting: &mut DenseBitSet<ContractId>,
    ) -> Result {
        if self.reachable.contains(contract_id) {
            return Ok(());
        }

        let contract = gcx.hir.contract(contract_id);
        if contract.kind.is_interface() || contract.kind.is_abstract_contract() {
            return Err(gcx
                .dcx()
                .err("cannot generate creation bytecode for non-deployable contract")
                .span(contract.span)
                .emit());
        }

        if !visiting.insert(contract_id) {
            return Err(gcx
                .dcx()
                .err("recursive contract creation bytecode dependency")
                .span(contract.span)
                .emit());
        }

        let dependencies = gcx.contract_bytecode_dependencies(contract_id);
        for dependency in dependencies {
            self.dependents[dependency].push(contract_id);
            self.discover_contract(gcx, dependency, visiting)?;
        }
        for dependency in dependencies {
            self.dependencies[contract_id].insert(dependency);
        }
        self.reachable.insert(contract_id);
        visiting.remove(contract_id);
        Ok(())
    }
}

fn spawn_contract_codegen<'scope, 'gcx>(
    scope: &Scope<'_, 'scope>,
    gcx: Gcx<'gcx>,
    captures: ContractCaptures<'scope>,
    graph: &'scope ContractGraph,
    artifacts: &'scope IndexVec<ContractId, OnceLock<ContractArtifact>>,
    remaining_dependencies: &'scope IndexVec<ContractId, AtomicUsize>,
    contract_id: ContractId,
) where
    'gcx: 'scope,
{
    scope.spawn(move |scope| {
        let Ok(artifact) = generate_contract_bytecode(gcx, contract_id, captures, graph, artifacts)
        else {
            return;
        };
        artifacts[contract_id]
            .set(artifact)
            .expect("contract artifact should only be generated once");

        for &dependent in &graph.dependents[contract_id] {
            let previous = remaining_dependencies[dependent].fetch_sub(1, Ordering::AcqRel);
            assert!(previous > 0, "contract dependency count underflow");
            if previous == 1 {
                spawn_contract_codegen(
                    &scope,
                    gcx,
                    captures,
                    graph,
                    artifacts,
                    remaining_dependencies,
                    dependent,
                );
            }
        }
    });
}

fn generate_contract_bytecode(
    gcx: Gcx<'_>,
    contract_id: ContractId,
    captures: ContractCaptures<'_>,
    graph: &ContractGraph,
    artifacts: &IndexVec<ContractId, OnceLock<ContractArtifact>>,
) -> Result<ContractArtifact> {
    let child_bytecodes = graph.dependencies[contract_id]
        .iter()
        .map(|dependency| {
            let bytecode = artifacts[dependency]
                .get()
                .expect("dependency artifact should have been generated")
                .deployment
                .clone();
            (dependency, bytecode)
        })
        .collect();
    let share_public_bodies = gcx.sess.opts.optimization.is_size();
    let mut module = lower::lower_contract_with_bytecodes_and_body_sharing(
        gcx,
        contract_id,
        &child_bytecodes,
        share_public_bodies,
    );
    gcx.dcx().has_errors()?;
    let capture_mir = captures.mir.contains(contract_id);
    let needs_backend = captures.bytecode.contains(contract_id)
        || captures.evm_ir.contains(contract_id)
        || !graph.dependents[contract_id].is_empty();
    let capture_built = capture_mir
        && matches!(gcx.sess.opts.optimization, OptimizationMode::None)
        && gcx.sess.opts.unstable.mir_pipeline.is_none();
    let built_mir = (capture_built && needs_backend).then(|| module.clone());
    let artifact = if needs_backend {
        let mut codegen = EvmCodegen::new(gcx);
        codegen.set_capture_mir(capture_mir && !capture_built);
        codegen.set_capture_evm_ir(captures.evm_ir.contains(contract_id));
        let mut artifact = codegen.lower_module(&mut module);
        gcx.dcx().has_errors()?;
        if gcx.sess.opts.optimization.is_gas()
            && gcx.sess.opts.evm_version >= EvmVersion::SpuriousDragon
            && artifact.runtime.len() > EIP170_RUNTIME_CODE_SIZE_LIMIT
            && artifact.runtime.len() <= EIP170_RUNTIME_CODE_SIZE_LIMIT * 2
        {
            let gas_first_module = module.clone();
            let gas_first_artifact = artifact;
            module = lower::lower_contract_with_bytecodes_and_body_sharing(
                gcx,
                contract_id,
                &child_bytecodes,
                true,
            );
            gcx.dcx().has_errors()?;
            let mut codegen = EvmCodegen::new(gcx);
            codegen.set_capture_mir(capture_mir && !capture_built);
            codegen.set_capture_evm_ir(captures.evm_ir.contains(contract_id));
            let size_rescue_artifact = codegen.lower_module(&mut module);
            gcx.dcx().has_errors()?;
            if size_rescue_artifact.runtime.len() <= EIP170_RUNTIME_CODE_SIZE_LIMIT {
                artifact = size_rescue_artifact;
            } else {
                module = gas_first_module;
                artifact = gas_first_artifact;
            }
        }
        artifact
    } else {
        if capture_mir && !capture_built {
            let _changed = run_pipeline(gcx, &mut module, None);
            gcx.dcx().has_errors()?;
        }
        Default::default()
    };
    let immutable_references = artifact
        .immutable_references
        .iter()
        .map(|reference| {
            let immutable = module.immutable(reference.id);
            ImmutableReference {
                variable_id: immutable
                    .variable_id
                    .expect("Solidity immutable must have a variable ID"),
                start: reference.code_offset + 1,
                type_size: reference.type_size,
            }
        })
        .collect();
    let mir = capture_mir.then(|| built_mir.unwrap_or(module));

    Ok(ContractArtifact {
        deployment: artifact.deployment.into(),
        runtime: artifact.runtime.into(),
        immutable_references,
        mir,
        deployment_evm_ir: artifact.deployment_evm_ir,
        runtime_evm_ir: artifact.runtime_evm_ir,
    })
}
